version: "3.6"
services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        environment:
            client_PORT: "8080"
            API_HOST: "http:localhost:8080"
        ports:
            - "8080:8080"
        volumes:
            - ./client/src:/app/src/
    # server:
    #     build: ./server/.
    #     ports:
    #         - "3443:3443"
